services:
  # The Backend Web Service (Node.js/Express)
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    repo: https://github.com/ShreyakTimsina/ExpenseTracker
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false # Render will prompt you to type this securely in the dashboard
      - key: JWT_SECRET
        generateValue: true # Render will automatically generate a secure 256-bit crypto string for this
